GOOSE_MODEL: us.anthropic.claude-3-7-sonnet-20250219-v1:0
GOOSE_PROVIDER: bedrock
extensions:
  computercontroller:
    enabled: true
    name: computercontroller
    timeout: 300
    type: builtin
  developer:
    enabled: true
    name: developer
    timeout: 300
    type: builtin
  jetbrains:
    enabled: true
    name: jetbrains
    timeout: 300
    type: builtin
  ktown4u-db:
    args:
      - jdbc@quarkiverse/quarkus-mcp-servers
      - jdbc:mariadb://hminter-r6g.cn1xjryhj9xq.ap-northeast-2.rds.amazonaws.com:3306/hmmall
      - -ubedrock
      - -pZ6>Z87G@a+7.
    cmd: jbang
    enabled: true
    envs: {}
    name: ktown4u_db
    timeout: null
    type: stdio
