import = [
    # "~/.config/alacritty/themes/themes/coolnight.toml"
    # "~/.config/alacritty/themes/themes/argonaut.toml"
    # "~/.config/alacritty/themes/themes/carbonfox.toml"
    # "~/.config/alacritty/themes/themes/catppuccin.toml"
    "~/.config/alacritty/themes/themes/dracula.toml"
    # "~/.config/alacritty/themes/themes/github_dark_high_contrast.toml"
    # "~/.config/alacritty/themes/themes/tokyo-night.toml"
]

[ env ]
TERM = "xterm-256color"

[window]
padding.x = 10
padding.y = 10

decorations = "Buttonless"

opacity = 0.8
blur = true

option_as_alt = "Both"

[font]
normal.family = "MesloLGS Nerd Font Mono"

#regular
size = 16

#for video
# size = 35.0
